# Generated by Django 5.2.4 on 2025-08-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="_"),
            preserve_default=False,
        ),
    ]
