# Generated by Django 5.2.4 on 2025-08-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggeditem",
            name="object_id",
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
