# Generated by Django 5.2.4 on 2025-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_taggeditem_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaggedItemManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
