# Generated by Django 5.2.4 on 2025-08-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_customer_store_custo_last_na_2e448d_idx"),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name="customer",
        #     name="store_custo_last_na_2e448d_idx",
        # ),
        # migrations.RemoveField(
        #     model_name="address",
        #     name="zip",
        # ),
        # migrations.RemoveField(
        #     model_name="cartitem",
        #     name="order",
        # ),
        # migrations.AddField(
        #     model_name="address",
        #     name="id",
        #     field=models.BigAutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.cart"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.customer"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
